/* DADOS ESTATICOS: adicione novos objetos seguindo este formato. */
const FLASHCARDS = [
  { word: 'time', translation: 'tempo', theme: 'Substantivos' },
  { word: 'person', translation: 'pessoa', theme: 'Substantivos' },
  { word: 'year', translation: 'ano', theme: 'Substantivos' },
  { word: 'way', translation: 'caminho, maneira', theme: 'Substantivos' },
  { word: 'day', translation: 'dia', theme: 'Substantivos' },
  { word: 'thing', translation: 'coisa', theme: 'Substantivos' },
  { word: 'man', translation: 'homem', theme: 'Substantivos' },
  { word: 'world', translation: 'mundo', theme: 'Substantivos' },
  { word: 'life', translation: 'vida', theme: 'Substantivos' },
  { word: 'hand', translation: 'mão', theme: 'Substantivos' },
  { word: 'part', translation: 'parte', theme: 'Substantivos' },
  { word: 'child', translation: 'criança', theme: 'Substantivos' },
  { word: 'eye', translation: 'olho', theme: 'Substantivos' },
  { word: 'woman', translation: 'mulher', theme: 'Substantivos' },
  { word: 'place', translation: 'lugar', theme: 'Substantivos' },
  { word: 'work', translation: 'trabalho', theme: 'Substantivos' },
  { word: 'week', translation: 'semana', theme: 'Substantivos' },
  { word: 'case', translation: 'caso', theme: 'Substantivos' },
  { word: 'point', translation: 'ponto', theme: 'Substantivos' },
  { word: 'government', translation: 'governo', theme: 'Substantivos' },
  { word: 'company', translation: 'empresa', theme: 'Substantivos' },
  { word: 'number', translation: 'número', theme: 'Substantivos' },
  { word: 'group', translation: 'grupo', theme: 'Substantivos' },
  { word: 'problem', translation: 'problema', theme: 'Substantivos' },
  { word: 'fact', translation: 'fato', theme: 'Substantivos' },
  { word: 'house', translation: 'casa', theme: 'Substantivos' },
  { word: 'family', translation: 'família', theme: 'Substantivos' },
  { word: 'student', translation: 'estudante', theme: 'Substantivos' },
  { word: 'system', translation: 'sistema', theme: 'Substantivos' },
  { word: 'area', translation: 'área', theme: 'Substantivos' },
  { word: 'money', translation: 'dinheiro', theme: 'Substantivos' },
  { word: 'story', translation: 'história', theme: 'Substantivos' },
  { word: 'month', translation: 'mês', theme: 'Substantivos' },
  { word: 'book', translation: 'livro', theme: 'Substantivos' },
  { word: 'water', translation: 'água', theme: 'Substantivos' },
  { word: 'example', translation: 'exemplo', theme: 'Substantivos' },
  { word: 'friend', translation: 'amigo', theme: 'Substantivos' },
  { word: 'school', translation: 'escola', theme: 'Substantivos' },
  { word: 'side', translation: 'lado', theme: 'Substantivos' },
  { word: 'kind', translation: 'tipo', theme: 'Substantivos' },
  { word: 'head', translation: 'cabeça', theme: 'Substantivos' },
  { word: 'name', translation: 'nome', theme: 'Substantivos' },
  { word: 'service', translation: 'serviço', theme: 'Substantivos' },
  { word: 'father', translation: 'pai', theme: 'Substantivos' },
  { word: 'power', translation: 'poder', theme: 'Substantivos' },
  { word: 'hour', translation: 'hora', theme: 'Substantivos' },
  { word: 'game', translation: 'jogo', theme: 'Substantivos' },
  { word: 'line', translation: 'linha', theme: 'Substantivos' },
  { word: 'end', translation: 'fim', theme: 'Substantivos' },
  { word: 'good', translation: 'bom', theme: 'Adjetivos' },
  { word: 'new', translation: 'novo', theme: 'Adjetivos' },
  { word: 'first', translation: 'primeiro', theme: 'Adjetivos' },
  { word: 'last', translation: 'último', theme: 'Adjetivos' },
  { word: 'long', translation: 'longo', theme: 'Adjetivos' },
  { word: 'great', translation: 'ótimo', theme: 'Adjetivos' },
  { word: 'little', translation: 'pequeno', theme: 'Adjetivos' },
  { word: 'own', translation: 'próprio', theme: 'Adjetivos' },
  { word: 'other', translation: 'outro', theme: 'Adjetivos' },
  { word: 'old', translation: 'velho', theme: 'Adjetivos' },
  { word: 'right', translation: 'certo, direito', theme: 'Adjetivos' },
  { word: 'big', translation: 'grande', theme: 'Adjetivos' },
  { word: 'high', translation: 'alto', theme: 'Adjetivos' },
  { word: 'different', translation: 'diferente', theme: 'Adjetivos' },
  { word: 'small', translation: 'pequeno', theme: 'Adjetivos' },
  { word: 'large', translation: 'grande', theme: 'Adjetivos' },
  { word: 'next', translation: 'próximo', theme: 'Adjetivos' },
  { word: 'early', translation: 'cedo', theme: 'Adjetivos' },
  { word: 'young', translation: 'jovem', theme: 'Adjetivos' },
  { word: 'important', translation: 'importante', theme: 'Adjetivos' },
  { word: 'few', translation: 'poucos', theme: 'Adjetivos' },
  { word: 'public', translation: 'público', theme: 'Adjetivos' },
  { word: 'bad', translation: 'ruim', theme: 'Adjetivos' },
  { word: 'same', translation: 'mesmo', theme: 'Adjetivos' },
  { word: 'able', translation: 'capaz', theme: 'Adjetivos' },
  { word: 'happy', translation: 'feliz', theme: 'Adjetivos' },
  { word: 'easy', translation: 'fácil', theme: 'Adjetivos' },
  { word: 'free', translation: 'livre', theme: 'Adjetivos' },
  { word: 'strong', translation: 'forte', theme: 'Adjetivos' },
  { word: 'hard', translation: 'difícil', theme: 'Adjetivos' },
  { word: 'clear', translation: 'claro', theme: 'Adjetivos' },
  { word: 'full', translation: 'cheio', theme: 'Adjetivos' },
  { word: 'far', translation: 'longe', theme: 'Adjetivos' },
  { word: 'late', translation: 'tarde', theme: 'Adjetivos' },
  { word: 'short', translation: 'curto', theme: 'Adjetivos' },
  { word: 'poor', translation: 'pobre', theme: 'Adjetivos' },
  { word: 'real', translation: 'real', theme: 'Adjetivos' },
  { word: 'black', translation: 'preto', theme: 'Adjetivos' },
  { word: 'white', translation: 'branco', theme: 'Adjetivos' },
  { word: 'simple', translation: 'simples', theme: 'Adjetivos' },
  { word: 'cold', translation: 'frio', theme: 'Adjetivos' },
  { word: 'personal', translation: 'pessoal', theme: 'Adjetivos' },
  { word: 'left', translation: 'esquerdo', theme: 'Adjetivos' },
  { word: 'dark', translation: 'escuro', theme: 'Adjetivos' },
  { word: 'fine', translation: 'fino', theme: 'Adjetivos' },
  { word: 'huge', translation: 'enorme', theme: 'Adjetivos' },
  { word: 'necessary', translation: 'necessário', theme: 'Adjetivos' },
  { word: 'hot', translation: 'quente', theme: 'Adjetivos' },
  { word: 'major', translation: 'principal', theme: 'Adjetivos' },
  { word: 'wide', translation: 'largo', theme: 'Adjetivos' },
  { word: 'be', translation: 'ser, estar', theme: 'Verbos' },
  { word: 'have', translation: 'ter', theme: 'Verbos' },
  { word: 'do', translation: 'fazer', theme: 'Verbos' },
  { word: 'say', translation: 'dizer', theme: 'Verbos' },
  { word: 'go', translation: 'ir', theme: 'Verbos' },
  { word: 'can', translation: 'poder', theme: 'Verbos' },
  { word: 'get', translation: 'obter, conseguir', theme: 'Verbos' },
  { word: 'make', translation: 'fazer', theme: 'Verbos' },
  { word: 'know', translation: 'saber, conhecer', theme: 'Verbos' },
  { word: 'think', translation: 'pensar', theme: 'Verbos' },
  { word: 'take', translation: 'tomar, pegar', theme: 'Verbos' },
  { word: 'see', translation: 'ver', theme: 'Verbos' },
  { word: 'come', translation: 'vir', theme: 'Verbos' },
  { word: 'want', translation: 'querer', theme: 'Verbos' },
  { word: 'use', translation: 'usar', theme: 'Verbos' },
  { word: 'find', translation: 'encontrar', theme: 'Verbos' },
  { word: 'give', translation: 'dar', theme: 'Verbos' },
  { word: 'tell', translation: 'contar, dizer', theme: 'Verbos' },
  { word: 'work', translation: 'trabalhar', theme: 'Verbos' },
  { word: 'call', translation: 'chamar, ligar', theme: 'Verbos' },
  { word: 'try', translation: 'tentar', theme: 'Verbos' },
  { word: 'ask', translation: 'perguntar', theme: 'Verbos' },
  { word: 'need', translation: 'precisar', theme: 'Verbos' },
  { word: 'feel', translation: 'sentir', theme: 'Verbos' },
  { word: 'become', translation: 'tornar-se', theme: 'Verbos' },
  { word: 'leave', translation: 'deixar, sair', theme: 'Verbos' },
  { word: 'put', translation: 'colocar', theme: 'Verbos' },
  { word: 'mean', translation: 'significar', theme: 'Verbos' },
  { word: 'keep', translation: 'manter', theme: 'Verbos' },
  { word: 'let', translation: 'deixar', theme: 'Verbos' },
  { word: 'begin', translation: 'começar', theme: 'Verbos' },
  { word: 'seem', translation: 'parecer', theme: 'Verbos' },
  { word: 'help', translation: 'ajudar', theme: 'Verbos' },
  { word: 'talk', translation: 'falar', theme: 'Verbos' },
  { word: 'turn', translation: 'virar', theme: 'Verbos' },
  { word: 'start', translation: 'iniciar', theme: 'Verbos' },
  { word: 'show', translation: 'mostrar', theme: 'Verbos' },
  { word: 'hear', translation: 'ouvir', theme: 'Verbos' },
  { word: 'play', translation: 'jogar, brincar', theme: 'Verbos' },
  { word: 'run', translation: 'correr', theme: 'Verbos' },
  { word: 'move', translation: 'mover', theme: 'Verbos' },
  { word: 'like', translation: 'gostar', theme: 'Verbos' },
  { word: 'live', translation: 'viver', theme: 'Verbos' },
  { word: 'believe', translation: 'acreditar', theme: 'Verbos' },
  { word: 'hold', translation: 'segurar', theme: 'Verbos' },
  { word: 'bring', translation: 'trazer', theme: 'Verbos' },
  { word: 'happen', translation: 'acontecer', theme: 'Verbos' },
  { word: 'write', translation: 'escrever', theme: 'Verbos' },
  { word: 'provide', translation: 'fornecer', theme: 'Verbos' },
  { word: 'sit', translation: 'sentar', theme: 'Verbos' },
  { word: 'stand', translation: 'ficar de pé', theme: 'Verbos' },
  { word: 'lose', translation: 'perder', theme: 'Verbos' },
  { word: 'I', translation: 'eu', theme: 'Pronomes' },
  { word: 'you', translation: 'você', theme: 'Pronomes' },
  { word: 'he', translation: 'ele', theme: 'Pronomes' },
  { word: 'she', translation: 'ela', theme: 'Pronomes' },
  { word: 'it', translation: 'ele, ela (neutro)', theme: 'Pronomes' },
  { word: 'we', translation: 'nós', theme: 'Pronomes' },
  { word: 'they', translation: 'eles, elas', theme: 'Pronomes' },
  { word: 'me', translation: 'mim', theme: 'Pronomes' },
  { word: 'him', translation: 'ele (objeto)', theme: 'Pronomes' },
  { word: 'her', translation: 'ela (objeto)', theme: 'Pronomes' },
  { word: 'us', translation: 'nós (objeto)', theme: 'Pronomes' },
  { word: 'them', translation: 'eles, elas (objeto)', theme: 'Pronomes' },
  { word: 'my', translation: 'meu, minha', theme: 'Pronomes' },
  { word: 'your', translation: 'seu, sua', theme: 'Pronomes' },
  { word: 'his', translation: 'dele', theme: 'Pronomes' },
  { word: 'her', translation: 'dela', theme: 'Pronomes' },
  { word: 'its', translation: 'dele, dela (neutro)', theme: 'Pronomes' },
  { word: 'our', translation: 'nosso, nossa', theme: 'Pronomes' },
  { word: 'their', translation: 'deles, delas', theme: 'Pronomes' },
  { word: 'very', translation: 'muito', theme: 'Adverbios' },
  { word: 'really', translation: 'realmente', theme: 'Adverbios' },
  { word: 'just', translation: 'apenas, só', theme: 'Adverbios' },
  { word: 'well', translation: 'bem', theme: 'Adverbios' },
  { word: 'quickly', translation: 'rapidamente', theme: 'Adverbios' },
  { word: 'slowly', translation: 'devagar', theme: 'Adverbios' },
  { word: 'now', translation: 'agora', theme: 'Adverbios' },
  { word: 'then', translation: 'então', theme: 'Adverbios' },
  { word: 'too', translation: 'também', theme: 'Adverbios' },
  { word: 'always', translation: 'sempre', theme: 'Adverbios' },
  { word: 'never', translation: 'nunca', theme: 'Adverbios' },
  { word: 'often', translation: 'frequentemente', theme: 'Adverbios' },
  { word: 'sometimes', translation: 'às vezes', theme: 'Adverbios' },
  { word: 'usually', translation: 'geralmente', theme: 'Adverbios' },
  { word: 'soon', translation: 'em breve', theme: 'Adverbios' },
  { word: 'late', translation: 'tarde', theme: 'Adverbios' },
  { word: 'here', translation: 'aqui', theme: 'Adverbios' },
  { word: 'there', translation: 'lá', theme: 'Adverbios' },
  { word: 'away', translation: 'longe', theme: 'Adverbios' },
  { word: 'far', translation: 'longe', theme: 'Adverbios' },
  { word: 'near', translation: 'perto', theme: 'Adverbios' },
  { word: 'yesterday', translation: 'ontem', theme: 'Adverbios' },
  { word: 'today', translation: 'hoje', theme: 'Adverbios' },
  { word: 'tomorrow', translation: 'amanhã', theme: 'Adverbios' },
  { word: 'together', translation: 'juntos', theme: 'Adverbios' },
  { word: 'apart', translation: 'separado', theme: 'Adverbios' },
  { word: 'almost', translation: 'quase', theme: 'Adverbios' },
  { word: 'quite', translation: 'bastante', theme: 'Adverbios' },
  { word: 'more', translation: 'mais', theme: 'Adverbios' },
  { word: 'less', translation: 'menos', theme: 'Adverbios' },
  { word: 'in', translation: 'em', theme: 'Preposicoes' },
  { word: 'on', translation: 'sobre, em', theme: 'Preposicoes' },
  { word: 'at', translation: 'em, no, na', theme: 'Preposicoes' },
  { word: 'by', translation: 'por, de', theme: 'Preposicoes' },
  { word: 'with', translation: 'com', theme: 'Preposicoes' },
  { word: 'about', translation: 'sobre', theme: 'Preposicoes' },
  { word: 'against', translation: 'contra', theme: 'Preposicoes' },
  { word: 'between', translation: 'entre', theme: 'Preposicoes' },
  { word: 'among', translation: 'entre', theme: 'Preposicoes' },
  { word: 'through', translation: 'através de', theme: 'Preposicoes' },
  { word: 'during', translation: 'durante', theme: 'Preposicoes' },
  { word: 'before', translation: 'antes de', theme: 'Preposicoes' },
  { word: 'after', translation: 'depois de', theme: 'Preposicoes' },
  { word: 'above', translation: 'acima de', theme: 'Preposicoes' },
  { word: 'below', translation: 'abaixo de', theme: 'Preposicoes' },
  { word: 'to', translation: 'para', theme: 'Preposicoes' },
  { word: 'from', translation: 'de', theme: 'Preposicoes' },
  { word: 'up', translation: 'para cima', theme: 'Preposicoes' },
  { word: 'down', translation: 'para baixo', theme: 'Preposicoes' },
  { word: 'inside', translation: 'dentro de', theme: 'Preposicoes' },
  { word: 'outside', translation: 'fora de', theme: 'Preposicoes' },
  { word: 'under', translation: 'debaixo de', theme: 'Preposicoes' },
  { word: 'over', translation: 'sobre', theme: 'Preposicoes' },
  { word: 'into', translation: 'para dentro de', theme: 'Preposicoes' },
  { word: 'out of', translation: 'para fora de', theme: 'Preposicoes' },
  { word: 'off', translation: 'fora de', theme: 'Preposicoes' },
  { word: 'near', translation: 'perto de', theme: 'Preposicoes' },
  { word: 'beside', translation: 'ao lado de', theme: 'Preposicoes' },
  { word: 'along', translation: 'ao longo de', theme: 'Preposicoes' },
  { word: 'across', translation: 'através de', theme: 'Preposicoes' },
  { word: 'and', translation: 'e', theme: 'Conjuncoes' },
  { word: 'but', translation: 'mas', theme: 'Conjuncoes' },
  { word: 'or', translation: 'ou', theme: 'Conjuncoes' },
  { word: 'so', translation: 'então', theme: 'Conjuncoes' },
  { word: 'because', translation: 'porque', theme: 'Conjuncoes' },
  { word: 'although', translation: 'embora', theme: 'Conjuncoes' },
  { word: 'if', translation: 'se', theme: 'Conjuncoes' },
  { word: 'when', translation: 'quando', theme: 'Conjuncoes' },
  { word: 'where', translation: 'onde', theme: 'Conjuncoes' },
  { word: 'while', translation: 'enquanto', theme: 'Conjuncoes' },
  { word: 'since', translation: 'desde', theme: 'Conjuncoes' },
  { word: 'until', translation: 'até', theme: 'Conjuncoes' },
  { word: 'unless', translation: 'a menos que', theme: 'Conjuncoes' },
  { word: 'though', translation: 'embora', theme: 'Conjuncoes' },
  { word: 'the', translation: 'o, a, os, as', theme: 'Determinantes' },
  { word: 'a', translation: 'um, uma', theme: 'Determinantes' },
  { word: 'an', translation: 'um, uma', theme: 'Determinantes' },
  { word: 'this', translation: 'este, esta', theme: 'Determinantes' },
  { word: 'that', translation: 'aquele, aquela', theme: 'Determinantes' },
  { word: 'these', translation: 'estes, estas', theme: 'Determinantes' },
  { word: 'those', translation: 'aqueles, aquelas', theme: 'Determinantes' },
  { word: 'my', translation: 'meu, minha', theme: 'Determinantes' },
  { word: 'your', translation: 'seu, sua', theme: 'Determinantes' },
  { word: 'his', translation: 'dele', theme: 'Determinantes' },
  { word: 'her', translation: 'dela', theme: 'Determinantes' },
  { word: 'its', translation: 'dele, dela (neutro)', theme: 'Determinantes' },
  { word: 'our', translation: 'nosso, nossa', theme: 'Determinantes' },
  { word: 'their', translation: 'deles, delas', theme: 'Determinantes' },
  { word: 'some', translation: 'alguns, algumas', theme: 'Determinantes' },
  { word: 'any', translation: 'qualquer, nenhum', theme: 'Determinantes' },
  { word: 'no', translation: 'nenhum, nenhuma', theme: 'Determinantes' },
  { word: 'every', translation: 'todo, toda', theme: 'Determinantes' },
  { word: 'each', translation: 'cada', theme: 'Determinantes' },
  { word: 'much', translation: 'muito(a)', theme: 'Determinantes' },
  { word: 'many', translation: 'muitos(as)', theme: 'Determinantes' },
  { word: 'more', translation: 'mais', theme: 'Determinantes' },
  { word: 'most', translation: 'a maioria', theme: 'Determinantes' },
  { word: 'little', translation: 'pouco(a)', theme: 'Determinantes' },
  { word: 'few', translation: 'poucos(as)', theme: 'Determinantes' },
  { word: 'one', translation: 'um', theme: 'Numerais' },
  { word: 'two', translation: 'dois', theme: 'Numerais' },
  { word: 'three', translation: 'três', theme: 'Numerais' },
  { word: 'four', translation: 'quatro', theme: 'Numerais' },
  { word: 'five', translation: 'cinco', theme: 'Numerais' },
  { word: 'six', translation: 'seis', theme: 'Numerais' },
  { word: 'seven', translation: 'sete', theme: 'Numerais' },
  { word: 'eight', translation: 'oito', theme: 'Numerais' },
  { word: 'nine', translation: 'nove', theme: 'Numerais' },
  { word: 'ten', translation: 'dez', theme: 'Numerais' },
  { word: 'eleven', translation: 'onze', theme: 'Numerais' },
  { word: 'twelve', translation: 'doze', theme: 'Numerais' },
  { word: 'thirteen', translation: 'treze', theme: 'Numerais' },
  { word: 'fourteen', translation: 'quatorze', theme: 'Numerais' },
  { word: 'fifteen', translation: 'quinze', theme: 'Numerais' },
  { word: 'sixteen', translation: 'dezesseis', theme: 'Numerais' },
  { word: 'seventeen', translation: 'dezessete', theme: 'Numerais' },
  { word: 'eighteen', translation: 'dezoito', theme: 'Numerais' },
  { word: 'nineteen', translation: 'dezenove', theme: 'Numerais' },
  { word: 'twenty', translation: 'vinte', theme: 'Numerais' },
  { word: 'thirty', translation: 'trinta', theme: 'Numerais' },
  { word: 'forty', translation: 'quarenta', theme: 'Numerais' },
  { word: 'fifty', translation: 'cinquenta', theme: 'Numerais' },
  { word: 'sixty', translation: 'sessenta', theme: 'Numerais' },
  { word: 'seventy', translation: 'setenta', theme: 'Numerais' },
  { word: 'eighty', translation: 'oitenta', theme: 'Numerais' },
  { word: 'ninety', translation: 'noventa', theme: 'Numerais' },
  { word: 'hundred', translation: 'cem', theme: 'Numerais' },
  { word: 'un-', translation: 'não, contrário de (unhappy – infeliz)', theme: 'Prefixos' },
  { word: 're-', translation: 'novamente (rewrite – reescrever)', theme: 'Prefixos' },
  { word: 'dis-', translation: 'oposto, negação (disagree – discordar)', theme: 'Prefixos' },
  { word: 'in-', translation: 'não (incorrect – incorreto)', theme: 'Prefixos' },
  { word: 'im-', translation: 'não (impossible – impossível)', theme: 'Prefixos' },
  { word: 'il-', translation: 'não (illegal – ilegal)', theme: 'Prefixos' },
  { word: 'ir-', translation: 'não (irregular – irregular)', theme: 'Prefixos' },
  { word: 'mis-', translation: 'errado (misunderstand – entender errado)', theme: 'Prefixos' },
  { word: 'over-', translation: 'excesso (overwork – trabalhar demais)', theme: 'Prefixos' },
  { word: 'under-', translation: 'abaixo, insuficiente (underpaid – mal pago)', theme: 'Prefixos' },
  { word: 'pre-', translation: 'antes (preview – prévia)', theme: 'Prefixos' },
  { word: 'post-', translation: 'depois (postgraduate – pós-graduado)', theme: 'Prefixos' },
  { word: 'anti-', translation: 'contra (antivirus – antivírus)', theme: 'Prefixos' },
  { word: 'inter-', translation: 'entre (international – internacional)', theme: 'Prefixos' },
  { word: 'co-', translation: 'junto (coworker – colega de trabalho)', theme: 'Prefixos' },
  { word: 'super-', translation: 'acima (superhero – super-herói)', theme: 'Prefixos' },
  { word: 'semi-', translation: 'metade (semicircle – semicírculo)', theme: 'Prefixos' },
  { word: 'multi-', translation: 'muitos (multicultural – multicultural)', theme: 'Prefixos' },
  { word: 'sub-', translation: 'abaixo (submarine – submarino)', theme: 'Prefixos' },
  { word: 'trans-', translation: 'através (transport – transportar)', theme: 'Prefixos' },
  { word: '-er', translation: 'pessoa que faz algo (teacher – professor)', theme: 'Sufixos' },
  { word: '-or', translation: 'agente (actor – ator)', theme: 'Sufixos' },
  { word: '-ist', translation: 'profissão ou especialista (scientist – cientista)', theme: 'Sufixos' },
  { word: '-ian', translation: 'profissão ou nacionalidade (musician – músico)', theme: 'Sufixos' },
  { word: '-ness', translation: 'estado ou qualidade (happiness – felicidade)', theme: 'Sufixos' },
  { word: '-ment', translation: 'resultado ou processo (development – desenvolvimento)', theme: 'Sufixos' },
  { word: '-tion', translation: 'ação ou processo (information – informação)', theme: 'Sufixos' },
  { word: '-sion', translation: 'ação ou processo (decision – decisão)', theme: 'Sufixos' },
  { word: '-ity', translation: 'qualidade (ability – habilidade)', theme: 'Sufixos' },
  { word: '-ship', translation: 'relação ou condição (friendship – amizade)', theme: 'Sufixos' },
  { word: '-ful', translation: 'cheio de (beautiful – bonito; maravilhoso)', theme: 'Sufixos' },
  { word: '-less', translation: 'sem (careless – descuidado)', theme: 'Sufixos' },
  { word: '-able', translation: 'capaz de (comfortable – confortável)', theme: 'Sufixos' },
  { word: '-ible', translation: 'capaz de (possible – possível)', theme: 'Sufixos' },
  { word: '-ous', translation: 'cheio de (dangerous – perigoso)', theme: 'Sufixos' },
  { word: '-ive', translation: 'que possui característica (creative – criativo)', theme: 'Sufixos' },
  { word: '-al', translation: 'relacionado a (natural – natural)', theme: 'Sufixos' },
  { word: '-ly', translation: 'forma advérbios (quickly – rapidamente)', theme: 'Sufixos' },
  { word: '-ing', translation: 'ação em andamento (studying – estudando)', theme: 'Sufixos' },
  { word: '-ed', translation: 'passado ou particípio (worked – trabalhou)', theme: 'Sufixos' },
  { word: '-en', translation: 'tornar (strengthen – fortalecer)', theme: 'Sufixos' },
  { word: '-ize', translation: 'transformar em (modernize – modernizar)', theme: 'Sufixos' },
  { word: '-ise', translation: 'transformar em (organise – organizar – inglês britânico)', theme: 'Sufixos' },
  { word: 'Hang on a sec', translation: 'Espera um segundo', theme: 'Expressoes Conversacionais' },
  { word: 'Give me a sec', translation: 'Me dá um segundo', theme: 'Expressoes Conversacionais' },
  { word: 'Let me think about it', translation: 'Deixa eu pensar', theme: 'Expressoes Conversacionais' },
  { word: 'It depends', translation: 'Depende', theme: 'Expressoes Conversacionais' },
  { word: 'More or less', translation: 'Mais ou menos', theme: 'Expressoes Conversacionais' },
  { word: 'Kind of', translation: 'Meio que', theme: 'Expressoes Conversacionais' },
  { word: 'Pretty much', translation: 'Quase isso', theme: 'Expressoes Conversacionais' },
  { word: 'You name it', translation: 'De tudo', theme: 'Expressoes Conversacionais' },
  { word: 'Whatever you say', translation: 'Como você quiser', theme: 'Expressoes Conversacionais' },
  { word: 'If you say so', translation: 'Se você diz', theme: 'Expressoes Conversacionais' },
  { word: 'I guess so', translation: 'Acho que sim', theme: 'Expressoes Conversacionais' },
  { word: 'I doubt it', translation: 'Duvido', theme: 'Expressoes Conversacionais' },
  { word: 'No way', translation: 'Sem chance', theme: 'Expressoes Conversacionais' },
  { word: 'Cut it out', translation: 'Para com isso', theme: 'Expressoes Conversacionais' },
  { word: 'Knock it off', translation: 'Larga mão disso', theme: 'Expressoes Conversacionais' },
  { word: 'Give it a rest', translation: 'Deixa quieto', theme: 'Expressoes Conversacionais' },
  { word: 'Let it go', translation: 'Deixa pra lá', theme: 'Expressoes Conversacionais' },
  { word: 'Forget about it', translation: 'Esquece isso', theme: 'Expressoes Conversacionais' },
  { word: 'Never mind', translation: 'Deixa pra lá', theme: 'Expressoes Conversacionais' },
  { word: 'So what?', translation: 'E daí?', theme: 'Expressoes Conversacionais' },
  { word: 'Who cares?', translation: 'Quem se importa?', theme: 'Expressoes Conversacionais' },
  { word: 'Big deal', translation: 'Grande coisa', theme: 'Expressoes Conversacionais' },
  { word: 'Are you okay?', translation: 'Você está bem?', theme: 'Expressoes Conversacionais' },
  { word: 'You alright?', translation: 'Tá tudo certo?', theme: 'Expressoes Conversacionais' },
  { word: 'Suit up', translation: 'Se prepara', theme: 'Expressoes Conversacionais' },
  { word: 'I gotta go', translation: 'Tenho que ir', theme: 'Expressoes Conversacionais' },
  { word: 'Catch you later', translation: 'Até mais', theme: 'Expressoes Conversacionais' },
  { word: 'See you around', translation: 'A gente se vê por aí', theme: 'Expressoes Conversacionais' },
  { word: 'Stay safe', translation: 'Se cuida', theme: 'Expressoes Conversacionais' },
  { word: 'Keep in touch', translation: 'Mantenha contato', theme: 'Expressoes Conversacionais' },
  { word: 'Where to?', translation: 'Pra onde?', theme: 'Expressoes Conversacionais' },
  { word: 'Your call', translation: 'Você decide', theme: 'Expressoes Conversacionais' },
  { word: 'No problem', translation: 'Sem problema', theme: 'Expressoes Conversacionais' },
  { word: 'No worries', translation: 'Relaxa', theme: 'Expressoes Conversacionais' },
  { word: 'Sounds good', translation: 'Parece bom', theme: 'Expressoes Conversacionais' },
  { word: 'That makes sense', translation: 'Faz sentido', theme: 'Expressoes Conversacionais' },
  { word: 'I see', translation: 'Entendi', theme: 'Expressoes Conversacionais' },
  { word: 'Got it', translation: 'Entendi', theme: 'Expressoes Conversacionais' },
  { word: 'Fair enough', translation: 'Justo', theme: 'Expressoes Conversacionais' },
  { word: 'Exactly', translation: 'Exatamente', theme: 'Expressoes Conversacionais' },
  { word: 'Absolutely', translation: 'Com certeza', theme: 'Expressoes Conversacionais' },
  { word: 'Definitely', translation: 'Definitivamente', theme: 'Expressoes Conversacionais' },
  { word: 'Of course', translation: 'Claro', theme: 'Expressoes Conversacionais' },
  { word: 'Not really', translation: 'Na verdade não', theme: 'Expressoes Conversacionais' },
  { word: 'Maybe', translation: 'Talvez', theme: 'Expressoes Conversacionais' },
  { word: 'Probably', translation: 'Provavelmente', theme: 'Expressoes Conversacionais' },
  { word: 'I hope so', translation: 'Espero que sim', theme: 'Expressoes Conversacionais' },
  { word: 'My bad', translation: 'Foi mal', theme: 'Expressoes Conversacionais' },
  { word: 'Take your time', translation: 'Sem pressa', theme: 'Expressoes Conversacionais' },
  { word: 'Go ahead', translation: 'Pode falar', theme: 'Expressoes Conversacionais' },
  { word: 'By the way', translation: 'A propósito', theme: 'Expressoes Conversacionais' },
  { word: 'Actually', translation: 'Na verdade', theme: 'Expressoes Conversacionais' },
  { word: 'To be honest', translation: 'Para ser sincero', theme: 'Expressoes Conversacionais' },
  { word: 'For real?', translation: 'Sério?', theme: 'Expressoes Conversacionais' },
  { word: 'Seriously?', translation: 'Sério mesmo?', theme: 'Expressoes Conversacionais' },
  { word: 'Believe me', translation: 'Acredite em mim', theme: 'Expressoes Conversacionais' },
  { word: 'Lucky you', translation: 'Que sorte a sua', theme: 'Expressoes Conversacionais' },
  { word: 'What a shame', translation: 'Que pena', theme: 'Expressoes Conversacionais' },
  { word: 'Take it easy', translation: 'Vai com calma', theme: 'Expressoes Conversacionais' },
  { word: 'Be careful', translation: 'Tome cuidado', theme: 'Expressoes Conversacionais' },
  { word: 'Watch out', translation: 'Cuidado', theme: 'Expressoes Conversacionais' },
  { word: 'Come on', translation: 'Ah, vamos!', theme: 'Expressoes Conversacionais' },
  { word: 'No kidding', translation: 'Sério mesmo', theme: 'Expressoes Conversacionais' },
  { word: 'You never know', translation: 'Nunca se sabe', theme: 'Expressoes Conversacionais' },
  { word: 'It happens', translation: 'Acontece', theme: 'Expressoes Conversacionais' },
  { word: 'At least', translation: 'Pelo menos', theme: 'Expressoes Conversacionais' },
  { word: 'For sure', translation: 'Com certeza', theme: 'Expressoes Conversacionais' },
  { word: 'Deal!', translation: 'Combinado!', theme: 'Expressoes Conversacionais' },
  { word: 'Count me in', translation: 'Pode contar comigo', theme: 'Expressoes Conversacionais' },
  { word: 'Maybe next time', translation: 'Talvez da próxima vez', theme: 'Expressoes Conversacionais' },]

const state = { theme: 'all', search: '', index: 0, flipped: false, known: 0, again: 0, queue: [], queueKey: '', mode: 'study', reviewCards: [] };
const $ = (selector) => document.querySelector(selector);
const filteredCards = () => FLASHCARDS.filter((card) => (state.theme === 'all' || card.theme === state.theme) && `${card.word} ${card.translation}`.toLowerCase().includes(state.search.toLowerCase()));
function shuffled(cards) {
  const result = [...cards];
  for (let index = result.length - 1; index > 0; index -= 1) {
    const randomIndex = Math.floor(Math.random() * (index + 1));
    [result[index], result[randomIndex]] = [result[randomIndex], result[index]];
  }
  return result;
}

function studyCards(forceShuffle = false) {
  const cards = state.mode === 'review' ? state.reviewCards : filteredCards();
  const key = `${state.mode}|${state.theme}|${state.search}`;
  if (forceShuffle || state.queueKey !== key || state.queue.length !== cards.length) {
    state.queue = shuffled(cards);
    state.queueKey = key;
    state.index = 0;
  }
  return state.queue;
}

function renderThemes() {
  const themes = [...new Set(FLASHCARDS.map((card) => card.theme))];
  $('#themeList').innerHTML = themes.map((theme) => `<button class="theme-item" data-theme="${theme}" type="button">└ ${theme} <span>${FLASHCARDS.filter((card) => card.theme === theme).length}</span></button>`).join('');
  $('#filterRow').innerHTML = ['all', ...themes].map((theme) => `<button class="filter-button ${theme === 'all' ? 'active' : ''}" data-theme="${theme}" type="button">${theme === 'all' ? 'TODOS OS TEMAS' : theme}</button>`).join('');
  document.querySelectorAll('[data-theme]').forEach((button) => button.addEventListener('click', () => { state.theme = button.dataset.theme; state.index = 0; state.queueKey = ''; update(); }));
}

function update() {
  const cards = studyCards();
  if (!cards.length) { $('#cardWord').textContent = 'VAZIO'; $('#cardHint').textContent = 'NENHUM REGISTRO ENCONTRADO'; $('#resultCount').textContent = '00'; return; }
  state.index = Math.min(state.index, cards.length - 1);
  const card = cards[state.index];
  $('#cardWord').textContent = state.flipped ? card.translation.toUpperCase() : card.word.toUpperCase();
  $('#faceLabel').textContent = state.flipped ? 'VERSO // PORTUGUÊS' : 'FRENTE // INGLÊS';
  $('#cardHint').innerHTML = state.flipped ? 'CLIQUE PARA VOLTAR À FRENTE <b>↗</b>' : 'CLIQUE PARA REVELAR A TRADUÇÃO <b>↗</b>';
  $('#cardTag').textContent = card.theme;
  $('#cardPosition').textContent = `${String(state.index + 1).padStart(2, '0')} / ${String(cards.length).padStart(2, '0')}`;
  $('#resultCount').textContent = String(cards.length).padStart(2, '0');
  $('#allCount').textContent = String(FLASHCARDS.length).padStart(2, '0');
  $('#progressBar').style.width = `${((state.index + 1) / cards.length) * 100}%`;
  document.querySelectorAll('[data-theme]').forEach((button) => button.classList.toggle('active', button.dataset.theme === state.theme));
  $('#knownCount').textContent = String(state.known).padStart(2, '0');
  $('#againCount').textContent = String(state.again).padStart(2, '0');
  $('#reviewCount').textContent = String(state.reviewCards.length).padStart(2, '0');
  const total = state.known + state.again;
  $('#accuracy').textContent = total ? `${Math.round((state.known / total) * 100)}%` : '--%';
}

function nextCard(result) {
  const cards = studyCards();
  const currentCard = cards[state.index];
  const reviewing = state.mode === 'review';
  if (result === 'known') state.known += 1;
  if (result === 'again') {
    state.again += 1;
    if (state.mode === 'study' && currentCard && !state.reviewCards.includes(currentCard)) state.reviewCards.push(currentCard);
  }
  if (state.mode === 'review' && result === 'known') {
    state.reviewCards.splice(state.index, 1);
    state.queueKey = '';
  }
  if (state.mode === 'review' && !state.reviewCards.length) state.mode = 'study';
  state.index = state.mode === 'review' ? (state.index + 1) % Math.max(state.reviewCards.length, 1) : reviewing ? 0 : (state.index + 1) % Math.max(studyCards().length, 1);
  state.flipped = false;
  update();
}
$('#flashcard').addEventListener('click', () => { state.flipped = !state.flipped; update(); });
$('#knownButton').addEventListener('click', () => nextCard('known'));
$('#againButton').addEventListener('click', () => nextCard('again'));
$('#searchInput').addEventListener('input', (event) => { state.search = event.target.value; state.index = 0; state.queueKey = ''; state.flipped = false; update(); });
$('#shuffleButton').addEventListener('click', () => { state.flipped = false; updateWithShuffle(); });
$('#reviewButton').addEventListener('click', () => { if (!state.reviewCards.length) return; state.mode = 'review'; state.index = 0; state.queueKey = ''; state.flipped = false; updateWithShuffle(); });
$('#resetButton').addEventListener('click', () => { state.index = 0; state.flipped = false; state.known = 0; state.again = 0; state.search = ''; state.mode = 'study'; state.reviewCards = []; state.queueKey = ''; $('#searchInput').value = ''; updateWithShuffle(); });
function updateWithShuffle() { studyCards(true); update(); }
document.addEventListener('keydown', (event) => { if (event.code === 'Space') { event.preventDefault(); $('#flashcard').click(); } if (event.key === 'ArrowRight') nextCard(); });
function tick() { $('#clock').textContent = new Date().toLocaleTimeString('pt-BR', { hour12: false }); }
renderThemes(); update(); tick(); setInterval(tick, 1000);
